### ISSUE TITLE
[ Feat ] seniorProfile timeSelect 부가 기능 구현

### ISSUE THREAD

**Issue by j-nary** [TEAM-SEONYAK/SEONYAK_CLIENT#104]
### 🔨 Issue

seniorProfile timeSelect 부가 기능 구현
이거 원래 timeSelect 브랜치에서 하다가 뇌절와서 나중으로 미뤄뒀던 기능입니다
이거까지 있었으면 2000줄 피알이었을 것이니까요 ㅋ

### ✅ To-do

- [ ] 토스터 UI 구현
- [ ] 토스터 로직 구현
- [ ] warning 로직 구현

### 📄 Reference

<img width="377" alt="image" src="https://github.com/user-attachments/assets/31495212-be03-416f-bb9a-2277d751d2fd">
