### ISSUE TITLE
[ Feat ] 선배 리스트 필터링할 칩 기능 구현

### ISSUE THREAD

**Issue by yarimu** [TEAM-SEONYAK/SEONYAK_CLIENT#106]
### 🔨 Issue

<img width="464" alt="스크린샷 2024-07-16 오전 4 28 03" src="https://github.com/user-attachments/assets/a73e4f6b-3f58-4984-bc26-03c52b740da4">

### ✅ To-do

- [x] 직무 칩 내보내기
- [x] 직무 칩 x 버튼 구현
- [x] x버튼  클릭시, 필터링 버튼 내 숫자 실시간 감소
- [x] 초기화버튼 클릭시, 숫자 칩 모두 제거

### 📄 Reference

x
