### ISSUE TITLE
[ Feat ] Onboarding additional

### ISSUE THREAD

**Issue by j-nary** [TEAM-SEONYAK/SEONYAK_CLIENT#118]
### 🔨 Issue

Onboarding 추가작업

### ✅ To-do

- [ ] 공통 컴포넌트 사용하기
- [ ] 직무 선택 구현
- [ ] 계열 선택 구현

**Comment by j-nary** [comment]
앗 승희언니가 이슈 파놨네 닫을게~ 들어가 ~
