### ISSUE TITLE
[ Feat ] 번호입력 단계, 이메일입력 단계 고도화 

### ISSUE THREAD

**Issue by lydiacho** [TEAM-SEONYAK/SEONYAK_CLIENT#119]
### 🔨 Issue

- 선배 플로우 : 번호 입력 단계 
- 후배 플로우 : 학교 이메일 입력 단계
고도화합니다 

### ✅ To-do

- [ ] 선배 번호 입력 단계
- [ ] 후배 번호 입력 단계
- [ ] 후배 이메일 입력 단계
