### ISSUE TITLE
[ Feat ] 최종 라이팅 및 누락된 뷰 반영 

### ISSUE THREAD

**Issue by lydiacho** [TEAM-SEONYAK/SEONYAK_CLIENT#129]
### 🔨 Issue

전체 둘러보며 최종UX 라이팅 및 자잘한 뷰 누락된 부분을 보강합니다 

### ✅ To-do

- [x] UX라이팅 반영 
- [x] 중복 닉네임 에러필드 추가 
- [x] 개인정보 입력 FullButton invalid 조건 추가 
- [x] 졸업 증명서 인증 - 인증 성공 모달
- [x] 졸업증명서 인증 완료 페이지 - input 모두 disabled로 막기 
- [x] 직무 선택 - 버튼 비활성화 조건 추가 
- [x] 연차 선택 - 화살표 아이콘 추가, select box radius 추가, 스크롤바 너비 확인, 버튼 비활성화 조건 추가 
- [x] 휴대폰 인증 - 버튼 비활성화 조건 추가, 가입된 계정 존재 모달(선/후배에 따라 해당 에러 다르게 처리 유의)
- [x] 이메일 인증 - 유효하지않은 이메일 에러필드 추가
