### ISSUE TITLE
[ Fix ] 모달, Full Button 레이아웃 조정

### ISSUE THREAD

**Issue by ijieun** [TEAM-SEONYAK/SEONYAK_CLIENT#206]
### 🔨 Issue

![image](https://github.com/user-attachments/assets/9072e7ea-f793-4729-89a7-6b740aba7a8f)
![image](https://github.com/user-attachments/assets/a2a9c2c6-1e1e-4aa1-a63e-b7c976f41330)
![image](https://github.com/user-attachments/assets/358e6baf-d02d-48ca-88da-df0b2716c6c9)

### ✅ To-do

- [ ] 모달 레이아웃 위치 조정
- [ ] Full Button 레이아웃 위치 조정
- [ ] 다음으로 버튼 위치 조정
