### ISSUE TITLE
[ Fix ] 구글 소셜 로그인 및 회원가입 문제 해결 

### ISSUE THREAD

**Issue by lydiacho** [TEAM-SEONYAK/SEONYAK_CLIENT#213]
### 🔨 Issue

구글 소셜 로그인과 회원가입 플로우 내에서 발생하는 문제들을 모두 해결합니다 

### ✅ To-do

- [ ] 소셜 로그인 통신 문제 해결 
- [ ] 회원가입 데이터 업데이트 문제 해결 
- [ ] 각종 플로우 연결
