### ISSUE TITLE
[ Refactor ] SeniorListFilter 리팩토링 

### ISSUE THREAD

**Issue by yarimu** [TEAM-SEONYAK/SEONYAK_CLIENT#215]
### 🔨 Issue

1.  스타일린트 미적용 부분 수정
2. 불필요한 주석 제거
3. 불필요한 프롭스 줄이기!
4. 깜빡임 제거

### ✅ To-do

- [x] 스타일린트 미적용 부분 수정
- [x] 불필요한 주석 제거
- [x] 불필요한 프롭스 줄이기 -> positionChipNum 
- [x] 깜빡임 제거

### 📄 Reference

장정안,,
https://github.com/ssi02014/react-query-tutorial?tab=readme-ov-file#Suspense
