### ISSUE TITLE
[ Fix ] 셀프 QA - 이전페이지 뒤로가기, 모달 위치 조정, 이미 있는 약속 alert 표시

### ISSUE THREAD

**Issue by ijieun** [TEAM-SEONYAK/SEONYAK_CLIENT#222]
### 🔨 Issue

셀프 QA를 진행하면서 발견한 이슈를 수정합니다.
1. 약속신청 페이지에서 뒤로가기 버튼을 눌렀을때 이전페이지가 아닌, 나의 약속 창으로 돌아가는 이슈를 해결합니다.

https://github.com/user-attachments/assets/f6e48327-b558-4cbc-90d4-ec30b7461a6c

2. 약속신청 버튼 클릭시 모달창의 위치를 조정합니다.
<img width="373" alt="스크린샷 2024-08-19 오후 10 11 43" src="https://github.com/user-attachments/assets/628b0780-1ac5-459c-b5b4-f2d25f8ee77d">

3. 이미 있는 약속을 신청할 시에 아무 액션 없이 400 axios error 가 뜨는 이슈 수정
alert창을 띄워서 액션을 주도록 수정합니다.

### ✅ To-do

- [ ] 약속신청 페이지에서 뒤로가기 버튼 선택시 juniorPromise 페이지로 이동하도록 수정
- [ ] 약속신청 모달창의 위치를 조정
- [ ] 이미 있는 약속을 신청할 시에 alert창으로 알려줌
