### ISSUE TITLE
[ Design ] SeniorProfilePage 프로필 등록 퍼블리싱

### ISSUE THREAD

**Issue by j-nary** [TEAM-SEONYAK/SEONYAK_CLIENT#25]
### 🔨 Issue

SeniorProfilePage 프로필 등록 퍼블리싱

### ✅ To-do

- [ ] 프로필 등록 1단계
- [ ] 프로필 등록 2단계
- [ ] 프로필 등록 3단계
