### ISSUE TITLE
[ Fix ] 자잘한 2차 QA 이슈 개선 

### ISSUE THREAD

**Issue by lydiacho** [TEAM-SEONYAK/SEONYAK_CLIENT#311]
### 🔨 Issue

자잘하게 고칠 수 있는 이슈들 묶어서 한번에 작업

### ✅ To-do

- [x] 이메일 입력 - 타이머로 인한 초단위 콘솔 출력 제거 
- [ ] 닉네임 변경 시 중복확인 체크 여부 초기화 
- [ ] 졸업증명서 첨부 input 첨부하기 버튼 클릭 안되는 이슈 개선 
- [ ] 졸업 증명서 인증 성공 모달 위치 조정 
- [ ] 데탑뷰 좌측 하단 흰 박스 제거 
- [ ] 선배 온보딩 완료 페이지 이미지 크기 조정
