### ISSUE TITLE
[ Feat ] QA 추가된 모달 구현

### ISSUE THREAD

**Issue by se0jinYoon** [TEAM-SEONYAK/SEONYAK_CLIENT#314]
### 🔨 Issue

QA 추가된 모달 구현

### ✅ To-do

- [x] [선배] 둘러보기 탭 -> 준비중이에요 모달
- [x] [선/후배] 마이페이지 -> 준비중이에요 모달
- [x] 헤더 알림 -> 알림은 문자를 확인해주세요! 모달
