### ISSUE TITLE
[ Fix ] JuniorPromisePage 커서 포인터 적용 및 스크롤바 없애기

### ISSUE THREAD

**Issue by yarimu** [TEAM-SEONYAK/SEONYAK_CLIENT#338]
### 🔨 Issue

커서 포인터 적용 및 스크롤바 없애기

### ✅ To-do

- [x] 바텀시트 클릭됐을때만 '적용할래요'버튼 커서 포인터 적용
- [x] 클릭 가능한 모든 것 커서 포인터 적용
- [x] 스크롤바 보이는 거 삭제 
- [x] 바뀐 헤더 적용

### 📄 Reference

.
