### ISSUE TITLE
[ Design ] 선후배 약속 리스트 뷰 가장 최근 약속 카드 컴포넌트 퍼블리싱 

### ISSUE THREAD

**Issue by se0jinYoon** [TEAM-SEONYAK/SEONYAK_CLIENT#45]
### 🔨 Issue

선후배 약속 리스트 뷰 가장 최근 약속 카드 컴포넌트 퍼블리싱 

<img width="409" alt="스크린샷 2024-07-09 오후 6 32 34" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/26b76b91-6f09-4668-be59-52e979195a11">

### ✅ To-do

- [ ] 가장 가까운 약속 칩 구현
- [ ] 약속시간까지 남은 시간 계산 util 함수
- [ ] 전체 레이아웃 잡고 선/후배에 따라 조건부 연결
