### ISSUE TITLE
[ Desgin ] JuniorPromise 하단 바 퍼블리싱

### ISSUE THREAD

**Issue by ijieun** [TEAM-SEONYAK/SEONYAK_CLIENT#52]
### 🔨 Issue

- 모든 버튼을 다 선택하지 않았을 때  
![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/99737532/5a10d711-cf0a-4c5b-86fa-3827acb6c2b8)
- (바텀시트 올라왔을때) 달력 날짜만 선택했을 때
![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/99737532/2e5f6390-3374-48c6-a6d5-73d9c572c976)
- (바텀시트 올라왔을 때) 달력 날짜 선택하고, 약속 시간 선택했을 때 
![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/99737532/ef6ad51f-73cf-4695-bd25-d53862328937)
- 모든 버튼을 다 클릭했을 때 
![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/99737532/8f9df7e6-7a61-4445-b22d-5cba326f996c)

### ✅ To-do

- [ ] 모든 버튼 선택 X
- [ ] 모든 버튼 선택 O
- [ ] (바텀시트) 달력 날짜 선택 O 시간 선택 X
- [ ] (바텀시트) 달력 날짜 선택 O 시간 선택 O
