### ISSUE TITLE
[ Design ] 후배 홈에서 선배 탐색하는 바텀시트 내 헤더 푸터 구현

### ISSUE THREAD

**Issue by yarimu** [TEAM-SEONYAK/SEONYAK_CLIENT#56]
### 🔨 Issue

- 구현해야하는 화면
<img width="188" alt="스크린샷 2024-07-10 오전 2 19 15" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/157878428/2595c0f9-b036-4362-bc79-b9191e1e8d2d">

여기서 헤더 푸터만! 

### ✅ To-do

- [x] 타이틀
- [x] 설명
- [x] 초기화버튼
- [x] 적용할래요 버튼
- [x] 임의의 버튼 클릭시 바텀시트 올라오기
- [x] 뒤에 화면은 어두워져야함
- [x] 버튼 누르거나 바깥 누르면 바텀시트 내려가기
- [x] 그동안의 컴포넌트 연결하기...

### 📄 Reference

x
