### ISSUE TITLE
[ Feat ] CTA 조건부 렌더링 

### ISSUE THREAD

**Issue by lydiacho** [TEAM-SEONYAK/SEONYAK_CLIENT#67]
### 🔨 Issue

CTA 스텝별로 조건부 렌더링 

### ✅ To-do

- [ ] 버튼 라이팅 상수 분리 
- [ ] 스텝에 따라 라이팅 조건부 렌더링 
- [ ] CTA 배치 수정
