### ISSUE TITLE
[ Feat ] SeniorProfilePage TimeSelect 제외 프로필 등록 step 구현

### ISSUE THREAD

**Issue by j-nary** [TEAM-SEONYAK/SEONYAK_CLIENT#72]
### 🔨 Issue

SeniorProfilePage TimeSelect 제외 프로필 등록 step 구현

### ✅ To-do

- [x] 도현이를 표현할 수 있는 문장 작성 페이지
- [x] 도현이의 경력과 수상이력 작성 페이지
- [x] 도현이의 후배들에게 들려주고 싶은 이야기 작성 페이지

### 📄 Reference

<img width="502" alt="image" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/83453646/28f0147c-b797-467a-879e-7197f026a736">
