### ISSUE TITLE
[ Feat ] Onboarding 바텀시트 구현

### ISSUE THREAD

**Issue by j-nary** [TEAM-SEONYAK/SEONYAK_CLIENT#84]
### 🔨 Issue

승희언니에게 사온 Onboarding 바텀시트를 구현해보겠슴니다람쥐

### ✅ To-do

- [x] 학교 검색 바텀시트
- [ ] 직무 검색 바텀시트
- [ ] 학과 검색 뷰에서 내부 콘텐츠

-> 직무검색, 학과 검색 등은 이슈를 따로 팔게요 피알을 분리하라는 지시를 받았습니다

### 📄 Reference

<img width="707" alt="image" src="https://github.com/user-attachments/assets/0e36979a-c46f-4c3b-a4c2-21ee0117c86b">
