### ISSUE TITLE
[ Design ] 캘린더 스타일, 레이아웃 조정

### ISSUE THREAD

**Issue by ijieun** [TEAM-SEONYAK/SEONYAK_CLIENT#92]
### 🔨 Issue

![image](https://github.com/user-attachments/assets/ba8d6e88-1411-4a1c-9ae3-757890bca4c0)

![image](https://github.com/user-attachments/assets/3c4e8b4c-ffe0-4aa8-aede-4697d86f17e6)

- 캘린더의 안맞는 레이아웃을 조정합니다. (오전, 오후 가려지는 부분 조정. )
- 캘린더 날짜, 시간 누르면 '적용하기' 버튼 파랗게 하기

### ✅ To-do

- [ ] 캘린더 깨진 레이아웃 조정 (오전, 오후 가려지는 부분 조정. )
- [ ] 캘린더 파란색 버튼 적용
- [ ] 시간 버튼 클릭하면 검정 글씨 버튼 적용
