### ISSUE TITLE
[ Feat ] JuniorPromise 후배 약속 신청 플로우 연결

### ISSUE THREAD

**Issue by ijieun** [TEAM-SEONYAK/SEONYAK_CLIENT#94]
### 🔨 Issue

- 후배 약속 신청 후 모달을 연결합니다.
- 약속 신청 완료 페이지로 이동합니다.
![image](https://github.com/user-attachments/assets/339f8ede-0db0-4449-baa4-822936179105)

### ✅ To-do

- [ ] 약속 신청 페이지에서 바텀바 클릭하면 모달 연결
- [ ] 모달에서 '적용'버튼 클릭하면 신청 완료 페이지로 이동
- [ ] 후배 약속 신청 페이지 플로우 연결
